"""add FK indexes and RESTRICT constraints

Revision ID: 2f220792f452
Revises: a1adb5f44153
Create Date: 2026-02-24 13:12:54.845153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f220792f452'
down_revision: Union[str, None] = 'a1adb5f44153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_hardware', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_hardware_hardware_item_id'), ['hardware_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_hardware_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('order_spools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_spools_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_spools_spool_id'), ['spool_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_spool_id'), ['spool_id'], unique=False)

    with op.batch_alter_table('print_job_spools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_job_spools_spool_id'), ['spool_id'], unique=False)

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_jobs_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_spool_id'), ['spool_id'], unique=False)

    with op.batch_alter_table('spools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spools_filament_type_id'), ['filament_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spools_manufacturer_id'), ['manufacturer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spools_manufacturer_id'))
        batch_op.drop_index(batch_op.f('ix_spools_filament_type_id'))

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_jobs_spool_id'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_order_id'))

    with op.batch_alter_table('print_job_spools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_job_spools_spool_id'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_spool_id'))
        batch_op.drop_index(batch_op.f('ix_orders_project_id'))

    with op.batch_alter_table('order_spools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_spools_spool_id'))
        batch_op.drop_index(batch_op.f('ix_order_spools_order_id'))

    with op.batch_alter_table('order_hardware', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_hardware_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_hardware_hardware_item_id'))

    # ### end Alembic commands ###
