"""initial schema

Revision ID: a1adb5f44153
Revises: 
Create Date: 2026-02-23 21:07:44.922267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1adb5f44153'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('electricity_rate_kwh', sa.Float(), nullable=False),
    sa.Column('printer_wattage', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('machine_depreciation_rate', sa.Float(), nullable=False),
    sa.Column('profit_margin_percent', sa.Float(), nullable=False),
    sa.Column('fixed_fee_per_order', sa.Float(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_events', sa.Text(), nullable=False),
    sa.Column('webhook_order_due_days', sa.Integer(), nullable=False),
    sa.Column('enable_shipping', sa.Boolean(), nullable=False),
    sa.Column('default_shipping_charge', sa.Float(), nullable=False),
    sa.Column('low_spool_threshold_g', sa.Float(), nullable=False),
    sa.Column('show_spool_location', sa.Boolean(), nullable=False),
    sa.Column('enable_hardware', sa.Boolean(), nullable=False),
    sa.Column('enable_projects', sa.Boolean(), nullable=False),
    sa.Column('enable_orders', sa.Boolean(), nullable=False),
    sa.Column('enable_products_on_hand', sa.Boolean(), nullable=False),
    sa.Column('enable_spool_negative_prevention', sa.Boolean(), nullable=False),
    sa.Column('minimum_spool_reserve_g', sa.Float(), nullable=False),
    sa.Column('enable_low_spool_alerts', sa.Boolean(), nullable=False),
    sa.Column('enable_tracking_id_auto_generation', sa.Boolean(), nullable=False),
    sa.Column('last_seen_version', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('jwt_secret', sa.String(length=128), nullable=True),
    sa.Column('app_secret', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='singleton_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filament_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hardware_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('purchase_url', sa.String(length=500), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('quantity_purchased', sa.Integer(), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model_url', sa.String(length=500), nullable=True),
    sa.Column('filament_grams', sa.Float(), nullable=True),
    sa.Column('print_time_hours', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_filaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filament_type_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color_note', sa.String(length=100), nullable=True),
    sa.CheckConstraint('position >= 1 AND position <= 6', name='check_project_filament_position'),
    sa.ForeignKeyConstraint(['filament_type_id'], ['filament_types.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'position', name='uq_project_filament_position')
    )
    op.create_table('project_hardware',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('hardware_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_item_id'], ['hardware_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filament_type_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('total_weight_g', sa.Float(), nullable=False),
    sa.Column('remaining_weight_g', sa.Float(), nullable=False),
    sa.Column('cost_per_kg', sa.Float(), nullable=False),
    sa.Column('msrp', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('normal_price', sa.Float(), nullable=True),
    sa.Column('is_sale_price', sa.Boolean(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('tracking_id', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filament_type_id'], ['filament_types.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('spool_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=200), nullable=True),
    sa.Column('custom_price', sa.Float(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_contact', sa.String(length=300), nullable=True),
    sa.Column('customer_location', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('shipping_charge', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('filament_grams_snapshot', sa.Float(), nullable=True),
    sa.Column('print_time_hours_snapshot', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['spool_id'], ['spools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_hardware',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('hardware_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Float(), nullable=False),
    sa.Column('hardware_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('hardware_brand_snapshot', sa.String(length=200), nullable=True),
    sa.Column('is_one_off', sa.Boolean(), nullable=False),
    sa.Column('one_off_name', sa.String(length=200), nullable=True),
    sa.Column('one_off_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_item_id'], ['hardware_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_spools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('spool_id', sa.Integer(), nullable=False),
    sa.Column('filament_grams', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('cost_per_kg_snapshot', sa.Float(), nullable=False),
    sa.CheckConstraint('position >= 1 AND position <= 6', name='check_order_spool_position'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spool_id'], ['spools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'position', name='uq_order_spool_position')
    )
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spool_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filament_used_g', sa.Float(), nullable=True),
    sa.Column('print_time_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('was_for_customer', sa.Boolean(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spool_id'], ['spools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_job_spools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('print_job_id', sa.Integer(), nullable=False),
    sa.Column('spool_id', sa.Integer(), nullable=False),
    sa.Column('filament_used_g', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 1 AND position <= 6', name='check_print_job_spool_position'),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spool_id'], ['spools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('print_job_id', 'position', name='uq_print_job_spool_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_job_spools')
    op.drop_table('print_jobs')
    op.drop_table('order_spools')
    op.drop_table('order_hardware')
    op.drop_table('orders')
    op.drop_table('spools')
    op.drop_table('project_hardware')
    op.drop_table('project_filaments')
    op.drop_table('projects')
    op.drop_table('manufacturers')
    op.drop_table('hardware_items')
    op.drop_table('filament_types')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
